### ISSUE TITLE
Make hardware run in mock mode to test plans

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/p99-bluesky#23]
### Goals
Acceptance criteria : 
- [ ] Make hardware run in mock mode to test plans.

### Tasks
 base on the goals, deduce the tasks required. check them off once they're done
- [x] Create a simple plan to do scan with sample stage and a detector. 
- [ ] Make it run in mock mode with detector generate different value each point as the stage move.
- [ ] Modify the plan so it go to the peak, com, max or min value.
