### ISSUE TITLE
Change modules name keep to standard

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/p99-bluesky#24]
### Goals
- [ ] Change modules name keep to standard

### Tasks
 base on the goals, deduce the tasks required. check them off once they're done
- [ ] Change modules name keep to standard
- [ ] make sure everything still work
