### ISSUE TITLE
Hit and hope fly scan.

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/p99-bluesky#34]
### Goals
One of the three scanning type needed for STXM.
Acceptance criteria : 
- [x] Flying scan where the motor moves to the starting point and start moving to toward the end point, during which the detector keep measuring as fast as it can until the endpoint is reached or stopped. 
- [x] Each measurement should matches with the motor position as closely as possible but do not have to be exact like step 
- [x] User should be able to define the two axis they want to scan, time they want it to take to cover the area and  count time on the detector, the software then calculate the speed needed to cover the scanning area and does the fast-STXM scan.  

### Tasks
- [x] Create 1d fly scan. 
- [x] Add an axis so, the user can do multiple lines of fast scan within one plan.
- [x] Add speed calculation  to allow user to do scan with time instead of speed. 
     1. Error checking, need to check the scan can actually be done, due to max/min speed restriction.
