### ISSUE TITLE
STXM step scan

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/p99-bluesky#36]
### Goals
Acceptance criteria : 
- [x]  Create a plan to do STXM step scan.

### Tasks
 base on the goals, deduce the tasks required. check them off once they're done
- [x] Create stats only area detector, (no real need to save the ccd image but will require the detector stats to be recorded.
- [x] Define the points/type for the grid scan. Possibly using scanspec](https://github.com/dls-controls/scanspec)
- [x] Does the scan.
