### ISSUE TITLE
Reproduce stm data using the new laser 

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/p99-bluesky#45]
### Goals
- [ ] Recreated the data collected here with bluesky: https://confluence.diamond.ac.uk/display/SSCC/Mapping+Test+Rig+P99

### Tasks
- [ ] Collect data using stxms plan with software fly scan and step scans.
- [ ] Use the script to reconstruct the data and compare the quility.
- [ ] All should be done with blueApi and nexus data writer.

### Related Resources
[Stxm plane](https://github.com/DiamondLightSource/p99-bluesky/blob/main/src/p99_bluesky/plans/stxm.py)

**Comment by Relm-Arrowny** [comment]
first images:
![image](https://github.com/user-attachments/assets/8f7843ab-89d6-4a5f-93cc-4b9b7a849d31)
