### ISSUE TITLE
Remove andor2 detector from p99-bluesky

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/p99-bluesky#51]
### Goals
- [x] Remove devices that moved into dodal.
### Tasks
- [x] Remove andor 2 and all its related test.
- [x] Make sure all plan tests still pass.
- [x] Everything still works on p99.
### Related Resources
https://github.com/DiamondLightSource/dodal/pull/807
